add_newline = true 

format = "$all"

[character]                            # The name of the module we are configuring is"character"
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[aws]
disabled = true
symbol = "îŒ½"

[buf]
symbol = "ï’"

[conda]
symbol = "ğŸ…’"

[dart]
symbol = "î˜"

[directory]
truncation_length = 0
read_only = "ï ½"

[docker_context]
symbol = "ïŒˆ"

[elixir]
symbol = "î‰µ"

[elm]
symbol = "î˜¬"

[git_branch]
symbol = "ï˜"

[golang]
symbol = "î˜§"

[haskell]
symbol = "î·"

[hg_branch]
symbol = "ï˜"

[java]
symbol = "î‰–"

[julia]
symbol = "î˜¤"

[memory_usage]
symbol = "ï¡š"

[nim]
symbol = "ïš¤"

[nix_shell]
symbol = "ï‹œ"

[nodejs]
symbol = "îœ˜"

[package]
symbol = "ï£–"

[rust]
symbol = "î¨"

